### ISSUE TITLE
Name countries

### ISSUE THREAD

**Issue by iMasterAle** [annexare/Countries#1]
Hi guys,

The name of some countries are not correct for [ISO](https://www.iso.org/obp/ui/#iso:code:3166:CZ).

e.g.: Czechia => Czech Republic

Thanks in advance

**Comment by z-ax** [comment]
Hi, thank you for report. You're right, this one was incorrect, fixed with v1.0.4.
Please, let me know if there are something else (or feel free to send a Pull Request directly).
