### ISSUE TITLE
Some countries contain diacritic characters

### ISSUE THREAD

**Issue by unpxre** [annexare/Countries#103]
### Data changes

I think some countries can be written like that:
Åland -> Aland
São Tomé and Príncipe -> Sao Tome and Principe
Réunion -> Reunion

### Sources
https://www.britannica.com/place/Sao-Tome-and-Principe

**Comment by dmythro** [comment]
@unpxre just checked, I think you are right and English names should probably contain only A-Z characters. I'll check this.
