### ISSUE TITLE
Enable tree shaking with countries-list

### ISSUE THREAD

**Issue by jraoult** [annexare/Countries#106]
### Use case for the feature
I realised when investigating the size of a bundle (bundled by webpack) `countries-list` was imported even if it was not directly used. This is because the package is not marked as side effect-free, cf. https://sgom.es/posts/2020-06-15-everything-you-never-wanted-to-know-about-side-effects/.

Would you consider adding the flag to `package.json`? I'm pretty sure the package is fully side-effect free, and everyone bundling code that uses it would benefit.

**Comment by dmythro** [comment]
Thanks, I'll check it out!
