### ISSUE TITLE
CommonJS or AMD dependencies can cause optimization bailouts

### ISSUE THREAD

**Issue by ciriousjoker** [annexare/Countries#112]
### Use case for the feature

Angular complains during build with this warning:

> Warning: /Users/ciriousjoker/Development/Github/DieRinge/dieringe/apps/website/src/app/components/checkout/checkout.component.ts depends on 'countries-list'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by dmythro** [comment]
Hey @ciriousjoker, I'm working on v3 here: #110 and it's ESM/CommonJS/IIFE, would be cool if you'd check it out :) 
Going a bit slow, but should be released somewhere this month (probably next week).

**Comment by ciriousjoker** [comment]
@dmythro I didn't get around to testing it (and still won't in the near future). I assume this is fixed because the linked PR is merged? If you think this is fixed, feel free to close it and I'll reopen/ping once I get around to testing it and it doesn't end up working.

**Comment by dmythro** [comment]
> @dmythro I didn't get around to testing it (and still won't in the near future). I assume this is fixed because the linked PR is merged? If you think this is fixed, feel free to close it and I'll reopen/ping once I get around to testing it and it doesn't end up working.

Alright, thanks! I suppose it should be fixed with v3 release. Until then please test on direct GitHub source — all required/built files are always in `/dist` here.
