### ISSUE TITLE
Data update: native field for Nepal

### ISSUE THREAD

**Issue by reetaa** [annexare/Countries#114]
### Data changes

In the `packages/countries/src/data/countries.ts` file, the `native` field is incorrect for `NP` object.

Nepal is correctly written as नेपाल in native language.

```
NP: {
  name: 'Nepal',
  native: 'नेपाल',
  ...
```

### Links & sources

Here is a valid source for this change:

https://en.wikipedia.org/wiki/Nepali_language

**Comment by dmythro** [comment]
Thanks, I'll check/update it with the final PR for the next release.
