### ISSUE TITLE
Validate PHP / Composer / Tests with new file structure

### ISSUE THREAD

**Issue by dmythro** [annexare/Countries#116]
The new file/dir structure can potentially break things on PHP / Composer package. Need to check it out.

**Comment by dmythro** [comment]
Hey @Radiergummi do you still use PHP & this lib? I've got a new file/dir structure, would be great if someone checked it out.
Also, maybe there are some suggestions etc, would really appreciate it. You did great input on this previously :)

**Comment by dmythro** [comment]
I'd move `composer.json` and `phpunit.xml` inside respected dirs. And preferably ignore everything unrelated to PHP (like `.npmignore` file does for NPM publishing).
Suppose, at least need to update `composer.json` — `autoload` section as I see, in order to make it work when installed.

**Comment by Radiergummi** [comment]
Actually, yeah! It’s happily chugging along and has processed about 4 billion records as of today :) 

I’ll try to get to this this week, alright?

**Comment by dmythro** [comment]
> Actually, yeah! It’s happily chugging along and has processed about 4 billion records as of today :)

Sounds awesome, @Radiergummi!

> I’ll try to get to this this week, alright?

That would be great! Wanna release v3 soon. Will prepare a changelog in README as well so you could align everything including your projects.

Overall, it has changed some data structures (mainly, no comma-separated strings anymore — arrays instead), and some important country data updates reported. Added support for transcontinental countries etc.

If we could optimise the composer package to contain only the required files would be awesome!

**Comment by dmythro** [comment]
Hey @Radiergummi, I submitted a PR with structural changes: #124. It should work as expected. Well, according to docs :) 

It would be great if you'd have a look. Wondering if `"archive.exclude"` change will help with not packaging unnecessary files to PHP or need to use `.gitattributes` — `export-ignore` feature.

Wondering if we need additional class methods I mentioned above, but can be a separate PR/update.

**Comment by dmythro** [comment]
Hey @Radiergummi, I've released v3.0 for NPM. In case you have something to add from PHP side let's do it, otherwise I'll probably bump the version as is to at least include all data/structure updates.
