### ISSUE TITLE
Avoid breakage of JavaScript Devtools due to inconsistent unicode behaviour

### ISSUE THREAD

**Issue by JannikGM** [annexare/Countries#119]
This plugin contains flag emojis which triggered https://bugzilla.mozilla.org/show_bug.cgi?id=1845093 for us.
I've also reported this bug for VSCode: https://github.com/microsoft/vscode/issues/188677

I think more should be done to prevent these bugs from being triggered (potentially by encoding these unicode symbols differently in the source-code.. or warning users that there might be issues, including potential workarounds).

**Comment by dmythro** [comment]
@JannikGM here's the util to generate emoji flag: [packages/countries/src/getEmojiFlag.ts](https://github.com/annexare/Countries/blob/main/packages/countries/src/getEmojiFlag.ts).

And here are recent [CJS](https://github.com/annexare/Countries/blob/main/dist/index.min.js) and [MJS](https://github.com/annexare/Countries/blob/main/dist/index.min.mjs) builds (see [`dist`](https://github.com/annexare/Countries/tree/main/dist)).

If you want a country code to emoji flag Record, there's additional data import you need to do, not loaded by default: [`dist/more/countries.emoji.min.js`](https://github.com/annexare/Countries/blob/main/dist/more/countries.emoji.min.js). Oh, just noticed there's no MJS file for that, but there is a [`dist/more/countries.emoji.min.json`](https://github.com/annexare/Countries/blob/main/dist/more/countries.emoji.min.json) :)
