### ISSUE TITLE
Implementing a backend API to store in database and fetch in API

### ISSUE THREAD

**Issue by torabian** [annexare/Countries#123]
### Use case for the feature

I was looking for list of countries to add them into my project, so I can access the data via API get/pagination/search features, also to reference these data in SQL from other tables.

Is there a room to submit my binaries as well here so people can download it?

Project is not open source itself, but is available for free as a bootstraper for backend.

**Comment by dmythro** [comment]
Hi, absolutely not! It is an open source project, no closed source binaries are possible here. Or any other binaries to be honest.

Please feel free to share your work as a separate project in this case if you think it makes sense.

Besides, there are so many tools around to generate a proper API, with type safety and anything you need.

**Comment by torabian** [comment]
Thanks for insights.
I will prepare a document and host it separately where, and then I would give the link here to be shared, if you liked.

Many thanks.
