### ISSUE TITLE
The type package export is broken for TS projects using moduleResolution node16/nodenext/bundler

### ISSUE THREAD

**Issue by jraoult** [annexare/Countries#125]
### Use case for the feature

When consuming `countries-list` from a typescript project with `moduleResolution`: `node16/nodenext/bundler` in the configuration, the types are not "found" and `tsc` errors:

```sh
error TS7016: Could not find a declaration file for module 'countries-list'. '[...]/node_modules/countries-list/index.min.mjs' implicitly has an 'any' type.
```
and then
```sh
There are types at '[...]/node_modules/countries-list/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'countries-list' library may need to update its package.json or typings.
```

See this comment for an example of what needs to be done https://github.com/gxmari007/vite-plugin-eslint/pull/60#issuecomment-1416264911, which would result (assuming `index.d.mts` is bundled as well):

```json
[...]
    ".": {
      "import": {
        "types": "./index.d.mts",
        "default": "./index.min.mjs"
      },
      "require": {
        "types": "./index.d.ts",
        "default": "./index.min.js"
      }
    }
[...]
```

**Comment by dmythro** [comment]
Hi, thanks, gonna check this out. Exports should already cover all of that.

**Comment by StijnMaenhautCZ** [comment]
I assume this is related. Installed `v3.0.1` on a Node v16.20.2 instance and getting the following error (using vanilla javascript, no typescript):

```
This dependency was not found: 
* countries-list in ./node_modules/thread-loader/dist/cjs.js??ref--3-0!./node_modules/
babel-loader/lib??ref--3-1!./node_modules/vue-loader/lib??vue-loader-options!./components
/forms/tp-configurator-contact-form.vue?vue&type=script&lang=js&, ./node_modules/thread-
loader/dist/cjs.js??ref--3-0!./node_modules/babel-loader/lib??ref--3-1!./node_modules/eslint-
loader!./components/forms/tp-contact-form/tp-contact-form.js?vue&type=script&lang=js& and 6 others
```

**Comment by dmythro** [comment]
@StijnMaenhautCZ how about Node 18 LTS? Node 16 reached its end of life already.

Could you please share easiest way to reproduce the issue? I tried v3 on all of my projects when released and it worked without issues.

Gonna definitely check it out soon.

**Comment by jraoult** [comment]
@dmythro here's a reproduction of the issue I initially reported: https://stackblitz.com/edit/typescript-nsv8tl?file=index.html. You can see the error `Cannot find module 'countries-list' or its corresponding type declarations.(2307)` in the `index.ts` file. Applying [the changes I described earlier](https://github.com/annexare/Countries/issues/125#issue-1899782830) to `packages.json` fixes it from my quick tests.

**Comment by dmythro** [comment]
@jraoult please verify if v3.0.4 works for you now.

**Comment by jraoult** [comment]
@dmythro seems all good now. Thanks for the quick fix.
