### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by calvinh8** [annexare/Countries#127]
I have `"countries-list": "3.0.5"` installed in my Turbo setup under the `constants` workspace in the packages folder. I don't have `type` specified in my `packages/constants/package.json`.

`packages/constants/src/index.ts`
```TypeScript
import { getCountryData } from 'countries-list'

console.log(getCountryData('TW'))
```

`packages/constants/tsconfig.json`
```json
{
  "compilerOptions": {
    "lib": ["ES2015"],
    "module": "CommonJS",
    "outDir": "./dist",
    "rootDir": "./src"
  },
  "exclude": ["node_modules"],
  "extends": "tsconfig/base.json",
  "include": ["src"]
}
```

Output:
```shell
$ ts-node --esm packages/constants/src/index.ts

/xxx/Library/pnpm/global/5/.pnpm/ts-node@10.9.1_@types+node@18.15.0_typescript@4.9.5/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /xxx/node_modules/.pnpm/countries-list@3.0.5/node_modules/countries-list/index.min.js from /xxx/packages/constants/src/index.ts not supported.
index.min.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.min.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /xxx/node_modules/.pnpm/countries-list@3.0.5/node_modules/countries-list/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```

### Attempt 1
```shell
$ ts-node --esm packages/constants/src/index.ts

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /xxx/packages/constants/src/index.ts
```

### Attempt 2
Tried changing a few config based on the article here but no luck https://javascript.plainenglish.io/how-to-correctly-use-typescript-module-import-syntax-and-settings-in-various-circumstances-e98bfa87f70f

### Attempt 3 (Worked)

I tried changing "type": "module" to "type": "commonjs" in /xxx/node_modules/.pnpm/countries-list@3.0.5/node_modules/countries-list/package.json and that worked great for me. But this change will not persist since it's modifying node_modules.

Is there a permanent workaround to properly import your module and run it in TypeScript?

**Comment by dmythro** [comment]
This is weird, I tested on one of my projects with turbo and it worked without any issues. Don't think I used `ts-node` though.

Thanks, gonna check it out.

**Comment by calvinh8** [comment]
> This is weird, I tested on one of my projects with turbo and it worked without any issues. Don't think I used `ts-node` though.
> 
> Thanks, gonna check it out.

I was trying to test the code first before moving on and saw the error. That was why I used `ts-node` to run the ts file to see.

**Comment by ciriousjoker** [comment]
Same issue here, although it's in the context of firebase cloud functions.

Deployment fails with this error:

> Got response code 400; body Failed to generate manifest from function source: Error [ERR_REQUIRE_ESM]: require() of ES Module /__redacted__/node_modules/countries-list/index.min.js from /__redacted__/dist/apps/__redacted-some-own-file__.js not supported.
> index.min.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
> Instead rename index.min.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /__redacted__/node_modules/countries-list/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

**Comment by dmythro** [comment]
So, the package is build the way that `.js` is a CJS file for require(), `.mjs` is ESM for import. You can check `packages/countries/tsup.config.ts` with build configuration and `dist/package.json` of this repo which describe all of that. Why this error happens I'm not sure yet, maybe I am missing something.

I didn't have any issues on any of my projects/monorepos so far. I don't really want to change module type as mowing towards ESM is the way now.

Open for suggestions, maybe I am missing something. Maybe changing (or removing) package "type" could fix the issue, I'll check it out.

**Comment by ciriousjoker** [comment]
@dmythro 
I refactored some stuff and ran into a different error message:
> Got response code 400; body Failed to generate manifest from function source: SyntaxError: Named export 'countries' not found. The requested module 'countries-list' is a CommonJS module, which may not support all module.exports as named exports.

After updating, this error went away. Thanks a lot!
_I assume the original error I commented about had the same underlying issue._

**Comment by dmythro** [comment]
Great! Glad it's alright now. Please fire an issue if there will be one. I didn't release hybrid ESM/CJS packages before this one, so thanks for reaching out.
