### ISSUE TITLE
Add TypeScript definition file

### ISSUE THREAD

**Issue by kyranjamie** [annexare/Countries#13]
Would be nice to bundle with a `.d.ts` file, allowing for out the box TypeScript support.

**Comment by z-ax** [comment]
Hi, thanks for proposal. I didn't work with TS enough, but feel free to drop a PR if you find this useful.

**Comment by z-ax** [comment]
Published in v2.3.0. @kyranjamie please check it out.

**Comment by z-ax** [comment]
A link to PR into DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22478
