### ISSUE TITLE
[Data update] remove `Kosovo` from the list of countries; not in `ISO 3166`

### ISSUE THREAD

**Issue by o-alexandrov** [annexare/Countries#132]
### Data changes

Kosovo should be removed from the list of countries.
Or the main `readme.md` file should be updated to mention the data is not conforming to `ISO 3166`

### Links & sources

- [ISO 3166 list of countries](https://www.iso.org/obp/ui/#search)
- [Related PR in a similar library](https://github.com/fannarsh/country-list/pull/42)

**Comment by dmythro** [comment]
User-assigned codes is a part of a standard. But I think it would be clearer for them to actually have a `temporary` or `userAssigned` flag set in order to properly differentiate.

> User-assigned code elements are codes at the disposal of users who need to add further names of countries, territories, or other geographical entities to their in-house application of ISO 3166-1, and the ISO 3166/MA will never use these codes in the updating process of the standard. The following alpha-2 codes can be user-assigned: AA, QM to QZ, XA to XZ, and ZZ.

> The code XK is being used by the European Commission the IMF, and SWIFT, the CLDR, and other organizations as a temporary country code for Kosovo.

See: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#User-assigned_code_elements
