### ISSUE TITLE
getCountryCode may not return for some valid countries

### ISSUE THREAD

**Issue by dezull** [annexare/Countries#137]
### Use case for the feature

For example, `getCountryCode("Cocos (Keeling) Islands")` won't return the correct country code, because of the parentheses in the country name.

### Examples or links

The `countryName` used in the RegExp in the function is not escaped, so characters such as parentheses are interpreted as special characters:

```javascript
const nameRegex = new RegExp('^' + countryName + '$', 'i')
```

The solution in https://github.com/annexare/Countries/issues/131 can fix this, or a slight modification:

```javascript
export const getCountryCode = (countryName: string): TCountryCode | false => {
  // Match exact country name, but case insensitive
  const country = countryName.toLowerCase();

  return (
    countryDataList.find(({ name, native }) =>
       country === name.toLowerCase() ||
       country === native.toLowerCase()
    )?.iso2 || false
  )
}
```

Maybe allowing something like "Cocos Islands" or "Keeling Islands" also makes sense?

**Comment by dmythro** [comment]
Hi, forgot about this. Someone could've make a PR :) But looks like no volunteers. I'll check it out and update tests to make sure those countries are found properly.

**Comment by dmythro** [comment]
@dezull @osztenkurden please check if v3.1.1 works for you. Increased test coverage so seems fine with any name now.
