### ISSUE TITLE
Add ES5 plain JS file into dist

### ISSUE THREAD

**Issue by jonathanong** [annexare/Countries#14]
any possibility of compiling the dist directory to es5 so that this can be used client-side with uglifyjs?

**Comment by z-ax** [comment]
Yeah, I was thinking about having this a week ago, but in vacation yet :)
Will definitely add.

**Comment by lattam** [comment]
Hi, can I ask what is the status of this feature ? It would help us a lot in our project. Thank you :)

**Comment by z-ax** [comment]
Hi, was a bit busy with other stuff, will check it today/tomorow - should be a relatively quick build update :)

**Comment by z-ax** [comment]
#15 implements, released in v2.1.0.
