### ISSUE TITLE
add outline geometry

### ISSUE THREAD

**Issue by noerw** [annexare/Countries#26]
Adding the geometry as a GeoJSON (Multi)Polygon (data eg from [natural earth data](https://github.com/AshKyd/geojson-regions)) would be a great addon for this dataset.

**Comment by z-ax** [comment]
There are bigger libraries with this kind of data, like [mledoze/countries](https://github.com/mledoze/countries). Did you mean data like this? Maybe, for this would be better to just use it combined? Only thing required is to convert ISO country codes, I suppose.
