### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by llccrr** [annexare/Countries#27]
Hi, I tried on Windows 7 with
Firefox Quantum 60.0.2
IE11 v 11.0.9
Chrome 67.0.33

The flag is not rendered, is it possible that it come from Windows 7 ?

**Comment by z-ax** [comment]
Hi, flags are Emoji. So, they are rendered if the system/browser supports them. I don't think Windows 7 supports Emoji as it works nowadays in modern desktop/mobile OS with regular updates.
