### ISSUE TITLE
Åland should not be included on countries list

### ISSUE THREAD

**Issue by michalzubkowicz** [annexare/Countries#36]
Åland it's an independent territory part of Finland but not considered as country

**Comment by z-ax** [comment]
Well, it is a god point. But this library was mainly created based on ISO codes and Åland has own one, even has own TLD (`AX`, `.ax`).

Maybe we could make it work with additional param, like we have for `rtl` in languages, so it can be filtered out easily if required?

**Comment by michalzubkowicz** [comment]
I understand but module is named "countries" not "ISO codes" :). 

Filtering could be great but i think that list should not contain this as country.

**Comment by matthias-b** [comment]
It's not "independent" - it's autonomous, with its own language (Swedish). Removing this would reduce the effectiveness of this library. I'd strongly recommend against it.

**Comment by z-ax** [comment]
Not gonna remove anything, on the contrary — plan to extend the library in a way features like this can be determined if required :)

And as always, different purpose builds will help with effective traffic/data usage.

**Comment by dmythro** [comment]
I'm thinking maybe we should add a `parent`, or `partOf` property to each country code, for cases like this (`parent: "FI"`). When the property exists, it means this entity is a part of another (and easy to filter in cases you really need to).
@matthias-b @michalzubkowicz

**Comment by dmythro** [comment]
But from the other hand, adding this immediately brings politics up (cases like Taiwan).
