### ISSUE TITLE
HK and TaiWan and Macao are one of provinces in China

### ISSUE THREAD

**Issue by zhoufeii** [annexare/Countries#46]
![image](https://user-images.githubusercontent.com/36029402/67273375-e4d4f200-f4f0-11e9-87e1-99c3b29caaf8.png)

![image](https://user-images.githubusercontent.com/36029402/67273352-dbe42080-f4f0-11e9-8a81-b566a08a3bc6.png)

![image](https://user-images.githubusercontent.com/36029402/67273412-f3230e00-f4f0-11e9-886c-7d390c2a1d36.png)

why HK and TaiWan have their capital ? they are one of provinces in China，please correct the mistakes

**Comment by z-ax** [comment]
Let me finally get the time and rework to a new major version, where data structures will be more clear, to both cover all existing codes and be able to list country-only codes.
I'll update this ticket as soon as it'll be done, hopefully pretty soon as it's already delayed from summer.

**Comment by 5kahoisaac** [comment]
HK, TaiWan, are not Chi-na, 光復香港，時代革命

**Comment by dennismuench** [comment]
Taiwan is NOT related to china in any form. @zhoufeii is pressing an absurd political agenda. Please don't fall for that...

**Comment by dmythro** [comment]
We are not about politics here.
As I am aware, this [question has no correct answer](https://en.wikipedia.org/wiki/Political_status_of_Taiwan) yet. But still, we are mainly about ISO codes, which Taiwan has :)

This library will maintain official international status of certain data.

If you have an idea how it should be stored in a better way I'll gladly take it into account.

**Comment by JoJk0** [comment]
The library should include all territories and countries including official claims, maybe introducing presets? Kind of like Google Maps looks different in certain parts of the world. Each country preset could have its own list of officially recognised countries so Mainland Chinese will stop moaning that Taiwan is not a country and vice-versa.

**Comment by dmythro** [comment]
Maybe we could store that kind of data. But alongside politics, if there is a code for a country, region or locale, we should have it at least for the legacy issues :)

Open for suggestions on every aspect of data here. That's why it is open source. You suggest a use case and possible solution/PR and we discuss this together. I'll try to make all features modular so it fist for everyone.

**Comment by willyou** [comment]
Taiwan is NOT related to China in any form...
The Internet is out there, just google it.

**Comment by dmythro** [comment]
@willyou if we're speaking about official data then:

> Taiwan, officially the Republic of China, is a country in East Asia. It shares maritime borders with the People's Republic of China to the northwest, Japan to the northeast, and the Philippines to the south. [Wikipedia](https://en.wikipedia.org/wiki/Taiwan)

And Google Maps shows it for me with this info, for example. About the rest — I've seen info and aware what happens (I think).

**Comment by jodik** [comment]
It's good to add to @zhoufeii that it's not just for China, but many other regions not recognized internationally, e.g. West Sahara has a country code here (EH) and a gazillion of others. No need to freak out.

**Comment by dmythro** [comment]
@jodik I don't see it as a political thing for this lib. If region has code — it will be here. Relations between regions / countries is another story, and probably always will have some changes to maintain as it's not static, wars still happen like now russia invaded Ukraine and tries to occupy at least some regions.

Other thing is, this library could have another name then :)
