### ISSUE TITLE
Include alpha-3 codes

### ISSUE THREAD

**Issue by clar-cmp** [annexare/Countries#54]
Would be nice to include these.

**Comment by z-ax** [comment]
Let's see if this information is needed, the use cases. At the moment I find it pretty rare, but if it helps we at least could put a JSON file with alpha-2 to alpha-3 codes from [here](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) (or any other valid source), like:
```json
{
  ...
  "ua": "ukr",
  ...
}
```

My intention is to have as small chunks of data as possible for use cases I know about. If you could help with this — feel free to submit a PR.

**Comment by clar-cmp** [comment]
At minimum, I think it'd be very helpful to include the alpha-3 code in the list alongside each country's data; that way, at least the mapping can be established somehow in the code. I personally am interested in mapping alpha-3 to alpha-2 (I actually have data that includes both on different fields, for some reason) and think it'd be nice to not have to import separate libraries for displaying the names and parsing the alpha-3 codes.

**Comment by clar-cmp** [comment]
This doesn't seem to be exported, just included as a data file. So, not closed?

**Comment by z-ax** [comment]
@clar-cmp yeah, after publish of v2.5.3 checked `.npmignore` that `data` is ignored for NPM, happens sometimes. Should be fine in 2.5.4.

But don't export for now from index intentionally, to not grow the main bundle. Whoever needs this case can import it from `/dist/` json file separately.

**Comment by clar-cmp** [comment]
Ah, fair. Makes sense.
