### ISSUE TITLE
Languages and associated scripts

### ISSUE THREAD

**Issue by trenskow** [annexare/Countries#57]
I needed a package with additional information about scripts and their association to languages, so I made this [localization-data](https://github.com/trenskow/localization-data), which builds on top of this package and then adds this data.

If you are interested in integrating it directly into this, I could integrate it and make a PR?

**Comment by z-ax** [comment]
Hey, cool, thanks for highlighting! Didn't have use cases for the scripts yet, but will check it out (or could simply link to your package somewhere in README later so people can find it easily). With next major update I'll embed a lot more data into this package and reformat data structures (mainly to use with JavaScript/TypeScript).

Let's have it open for now, while working on v3.

**Comment by trenskow** [comment]
That sounds cool!

I needed a way to validate [BCP 47 tags](https://tools.ietf.org/html/bcp47), so that's why I made it.

Use it for whatever you like. I've used your package in a lot of applications by now, because I really find it the best of all the country / language data libraries out there for Node.

Just reach out to me if you have any further questions.

**Comment by dmythro** [comment]
I believe this data is better to be separately as it is a specific use case, and to now grow in the bundle size.
