### ISSUE TITLE
Estonian language

### ISSUE THREAD

**Issue by cgerikj** [annexare/Countries#59]
"ee" in languages.json should be Estonian instead of Ewe as  "EE" in countries.json is for Estonia.

**Comment by z-ax** [comment]
Current data is correct. Looks like you read data format incorrectly.
ISO 3166 code for Estonia is `EE`. ISO 639-1 code for Estonian language is `et`, as stated here.

See:
- https://en.wikipedia.org/wiki/Estonia
- https://en.wikipedia.org/wiki/Estonian_language
