### ISSUE TITLE
gibraltar country is missing area code

### ISSUE THREAD

**Issue by whimzyLive** [annexare/Countries#61]
"gibraltar" country does not have country phone code.
 Country Code: +350

**Comment by z-ax** [comment]
Thanks! Shall you create a quick PR, or me? :) 
Next time please specify a proof-link, at least a [Wiki](https://en.wikipedia.org/wiki/Gibraltar) page.

**Comment by z-ax** [comment]
Actually, checked again and see that Gibraltar always had proper phone code:

```json
  "GI": {
    "name": "Gibraltar",
    "native": "Gibraltar",
    "phone": "350",
...
```
