### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by Triplecorpse** [annexare/Countries#64]
### Use case for the feature

Looks like a great library. I'd just could propose to designate source of the data and its update rate in README.MD. I have read in the issues that you base on ISO information but I don't think that you buy official info for 300 CHF and give it to us free, right?

**Comment by z-ax** [comment]
Hi! At the moment of creation I used compilation from several open data sources. After release I accept PRs on data updates, usually people who use are aware of the important changes at least around.

Also, as I work on v3, started on automated solution to check for updates on regular basis. Plan to check data from Wiki as well and actual sources I'll have.

Good question overall, I'm absolutely open for any suggestions on this. Closing issue for now, but feel free to comment or re-open on updates.
