### ISSUE TITLE
Update KY language name

### ISSUE THREAD

**Issue by xcopy** [annexare/Countries#70]
### Data changes
Please, **Kirghiz** should be changed to (exactly) **Kyrgyz**. Cus *Kyrgyz* is the official language of Kyrgyz Republic.
https://github.com/annexare/Countries/blob/master/data/languages.json#L366

### Links & sources
Here is a valid source for this change:
https://en.wikipedia.org/wiki/Kyrgyz_language

**Comment by z-ax** [comment]
@xcopy let's make an update for this. Is native name correct (`Kırgızca / Кыргызча`)?

**Comment by xcopy** [comment]
@z-ax, actually you can ignore/remove `Kırgızca` and just keep `Кыргызча`.

Final result should be:
```
"ky": {
   "name": "Kyrgyz",
   "native": "Кыргызча"
}
````

**Comment by z-ax** [comment]
@xcopy, that's why I asked, thanks!

**Comment by z-ax** [comment]
Released in v2.5.6.
