### ISSUE TITLE
countries2to3 and countries3to2 not exported via TS definition 

### ISSUE THREAD

**Issue by phawxby** [annexare/Countries#73]
### Use case for the feature
Simplified the import process rather than needing multiple. 
```
import { countries } from 'countries-list';
import countries2to3 from 'countries-list/dist/countries2to3.json';
```

### Examples or links
Other JSON files are exported.
https://github.com/annexare/Countries/blob/master/dist/index.js#L3-L6

**Comment by dmythro** [comment]
Those files aren't exported by the main module as it's quite a rare use case, no need for extra bundle size to load (up to 8KB).

**Comment by dmythro** [comment]
This data will also have type definitions with #83 merged.
Check #85 for more details on upcoming v3 update.
