### ISSUE TITLE
es5 dist output not es5?

### ISSUE THREAD

**Issue by guybowden** [annexare/Countries#81]
I'm not totally up on my es5, es6 - but I _think_ that the `let` keyword is es6 only?

yet the main `dist/index.es5.min.js` contains the `let` keyword since v2.6.0 - causing my webpack build to fail as it's expecting es5 

![Screenshot_20210216_104941](https://user-images.githubusercontent.com/140627/108046248-b0216e00-7044-11eb-8c05-0f5a992ce551.png)

**Comment by dmythro** [comment]
Hey, thanks for reporting.
That's weird as `terser` has `{ ecma: 5, ie8: true }`. But I have a feeling it doesn't process ponycode built-in.

**Comment by dmythro** [comment]
FYI: working on migration to TypeScript in #83. That will also fix ES5 exports.
