### ISSUE TITLE
Data update

### ISSUE THREAD

**Issue by faridmdnor** [annexare/Countries#82]
### Data changes

Need to update for Malaysia's states
Kuala Lumpur, update to 'WP Kuala Lumpur'

Add two more;
WP Putrajaya
WP Labuan

WP stands for Wilayah Persekutuan.

### Links & sources

Here is a valid source for this change:

**Comment by dmythro** [comment]
@faridmdnor is there a link with official info on this?

**Comment by faridmdnor** [comment]
https://en.m.wikipedia.org/wiki/States_and_federal_territories_of_Malaysia

Federal Territories in Malay language means Wilayah Persekutuan.

**Comment by dmythro** [comment]
@faridmdnor I think you are missing the purpose of the library. It's about ISO country/region codes. If there is no code, at this point there is no record here. And I don't see a reason to rename as official names remain the same, without "WP".
