### ISSUE TITLE
Description Update (Minor)

### ISSUE THREAD

**Issue by Jeonghyeock** [annexare/Countries#90]
<img width="763" alt="스크린샷 2021-06-21 오후 3 20 51" src="https://user-images.githubusercontent.com/52453875/122715780-5eb01680-d2a4-11eb-89ff-4bfd8e85c2ae.png">

It seems to be used ISO-4217 for currencyCodes, so the description would like to be updated with details.

**Comment by dmythro** [comment]
Thanks, updated.
