### ISSUE TITLE
Helper functions

### ISSUE THREAD

**Issue by seanonthenet** [annexare/Countries#96]
Some helper functions would be useful eg: `getCode = (countryName: string) => string` returning the country code. 

Also this would help a lot if paired with #35 so lookups of codes from alternative country names could be much more reliable.

**Comment by dmythro** [comment]
Adding some helpers with TypeScript upgrade. I should've release that a long time ago 🙁

**Comment by seanonthenet** [comment]
Thanks - looking forward to it
